//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotelmage
    {
        public int id { get; set; }
        public Nullable<int> Hotelid { get; set; }
        public byte[] imageSource { get; set; }
    
        public virtual hotel hotel { get; set; }
    }
}
